### PR TITLE
Add Finnish translation and change English to specify things

### PR DESCRIPTION
**Pull request by Dakoriki**
I made a Finnish translation and while making it I made some changes that I felt would be beneficial to change. Those changes I also made in the English translation. Mostly just specifying used units and making the description more descriptive.

I'm not sure if the units for wind speed are actually m/s. Couldn't really find that one out.
I'm not sure about daily forecast either. Should it be Use, Add or Active?
Also I don't see a need for a British English translation since nothing is different in it. And 'English (GB)' defaults to en.json when en-GB.json is not available anyway. Also the en-GB file was out of date as well, so...

### CODE REVIEW

**Comment by vesatakomo** [comment]
Hi !
FMI uses m/s for wind speed unit.

**Comment by cruwaller** [comment]
Thanks! And sorry for a delay!

> I'm not sure about daily forecast either. Should it be Use, Add or Active?

I don't have any strict opinion about this. I am (at least) just fine with `activate`... If it is OK for you.

**Comment by Dakoriki** [comment]
When I tested out the daily mode, I thought the tick box got unticked every time saved the current settings so I thought possibly using another word than activate might have been better. 
However I now see that it does stay on when you have the daily entity active so I'm fine with activate as well.

**Comment by cruwaller** [comment]
Ok, let merge this and hit an another PR if not good in the end :)

**Pull request merged**
