### PR TITLE
Change Home Assistant's depracated forecast property.

### LINKED ISSUE #68: New release 2023.9 will abandon forecast attribute for weather entities
https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

So the warning reported on my setup:
```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:339
Integration: Weather (documentation, issues)
First occurred: 08:54:47 (1 occurrences)
Last logged: 08:54:47

custom_components.fmi.weather::None is using a forecast attribute on an instance of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please report it to the custom integration author.
```
I think you noticed this issue yourself so I decided to create the ticket for tracking purposes only :)

### PR DESCRIPTION
**Pull request by cruwaller**
Fixes #68

### CODE REVIEW

**Comment by slovdahl** [comment]
Friendly reminder @anand-p-r - this will break in next month's Home Assistant release.

**Comment by JoukoT** [comment]
Hi

 

it seems that there is a fix for that.

 

 <https://github.com/cruwaller/fmi-hass-custom> GitHub - cruwaller/fmi-hass-custom: Home Assistant Custom Component Supporting FMI Based Weather and Sensor Platforms

 

at least it works for me.

 

 

 

 

Lähettäjä: Sebastian Lövdahl ***@***.***> 
Lähetetty: lauantai 10. helmikuuta 2024 20.11
Vastaanottaja: anand-p-r/fmi-hass-custom ***@***.***>
Kopio: Subscribed ***@***.***>
Aihe: Re: [anand-p-r/fmi-hass-custom] Change Home Assistant's depracated forecast property. (PR #69)

 

Friendly reminder @anand-p-r <https://github.com/anand-p-r>  - this will break in next month's Home Assistant release.

**Comment by cruwaller** [comment]
I hope so as well.
I can collect PRs for now if @anand-p-r is not willing to maintain the og version anymore... I would like to create a group to keep all in one place but hopefully @anand-p-r could create it 👌

**Comment by fursov** [comment]
Seems @anand-p-r does not visit this place anymore :(
Would it be possible for anyone, e.g. @cruwaller, to fork the repo and continue maintenance of the integration?
Or what would be the best way to procced here?

**Comment by cruwaller** [comment]
I created a new organization to keep this maintained. Please let me know if any of you wanna join the party :) 
Fork can be found from here https://github.com/fmi-hass/fmi-hass-custom

I will merge and push modifications in to get this work ongoing...

**Comment by cruwaller** [comment]
> I created a new organization to keep this maintained. Please let me know if any of you wanna join the party :) Fork can be found from here https://github.com/fmi-hass/fmi-hass-custom
> 
> I will merge and push modifications in to get this work ongoing...

This repo will be moved for easier user actions. I deleted the for now.... Sorry for the inconveniences!

**Comment by slovdahl** [comment]
@cruwaller @anand-p-r are you planning to make a new release of the integration as well? Home Assistant 2024.3 is being released later tonight.

**Comment by cruwaller** [comment]
Oh, very good point! I will trigger a release now with these changes. 
Thanks

**Pull request merged**
